server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watchh
    username: root
    password: Nah1211zz@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#  security:
#    user:
#      name: anhhuy
#      password: Nah1211zz@